version: '3'

services:
  pawtnerup_backend_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pawtnerup_backend_app
    container_name: pawtnerup_backend_app
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - pawtnerup_db
  pawtnerup_db:
    image: postgres:14.0-alpine
    container_name: pawtnerup_db
    env_file:
      - .env
    volumes: 
      - pawtnerup_db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:8003:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pawtnerup_db_data:
